In [ ]:
https://github.com/pytorch/ao/tree/main/torchao/optim
https://pytorch.org/blog/pytorch-native-architecture-optimization/

https://arxiv.org/pdf/2502.10940

# Project Index

[Custom Model Notebook](../../../notebooks/custom_model.ipynb)  
[Training Notebook](../../../notebooks/train.ipynb)  
[Project Config Notebook](../../../notebooks/project_config.ipynb)  
[Forgather Notebook](../../../notebooks/forgather.ipynb)  

In [2]:
import forgather.nb.notebooks as nb

nb.display_project_index(config_template="hfadafactor.yaml", show_pp_config=True, show_generated_code=False)

/opt/conda/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/opt/conda/lib/python3.10/site-packages/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(


## Dynamic Models

This is a demonstraction of how to perform model archetecture experiments by using the configuration system to dynamically change module types.

As most of the examples, we use "Tiny Causal" as a baseline, then make various changes for comparison.

### Common Configuration
- Tokenizer: tokenizers/tiny_2k_bpe.yaml
    - Vocabulary Size: 2000
    - Maximum Model Sequence: 2048
- Dataset: datasets/tiny/tiny_stories_abridged.yaml
    - Dataset ID: roneneldan/TinyStories
    - Reference: https://arxiv.org/abs/2305.07759
    - Train Select Range: 10% 
- Model:
    - Model Dimension: 256
    - MLP Dimension: 1024
    - Layers: 4
    - Heads: 2
    - All Dropout Probabilities: 0.0
- Trainer:
    - Class: aiws.trainer.Trainer
    - Epochs: 1
    - Initial Learning Rate: 1.0e-3
    - Train Batch Size: 32
    - LR Sheduler: Cosine

#### Project Directory: "/home/dinalt/ai_assets/forgather/examples/trainers/optimizers"

## Meta Config
Meta Config: [/home/dinalt/ai_assets/forgather/examples/trainers/optimizers/meta.yaml](meta.yaml)

- [meta.yaml](meta.yaml)
    - [meta_defaults.yaml](../../../forgather_workspace/meta_defaults.yaml)
        - [base_directories.yaml](../../../forgather_workspace/base_directories.yaml)

Template Search Paths:
- [/home/dinalt/ai_assets/forgather/examples/trainers/optimizers/templates](templates)
- [/home/dinalt/ai_assets/forgather/forgather_workspace](../../../forgather_workspace)
- [/home/dinalt/ai_assets/forgather/templates/tiny_experiments](../../../templates/tiny_experiments)
- [/home/dinalt/ai_assets/forgather/templates/modellib](../../../templates/modellib)
- [/home/dinalt/ai_assets/forgather/templates/base](../../../templates/base)

## Available Configurations
- [ngema_r128.yaml](templates/experiments/ngema_r128.yaml)
- [hfadafactor.yaml](templates/experiments/hfadafactor.yaml)
- [xnormgrad1-r128.yaml](templates/experiments/xnormgrad1-r128.yaml)
- [adafactor.yaml](templates/experiments/adafactor.yaml)
- [xnormgrad1-r1.yaml](templates/experiments/xnormgrad1-r1.yaml)
- [norm_grad.yaml](templates/experiments/norm_grad.yaml)
- [xng2_3.yaml](templates/experiments/xng2_3.yaml)
- [ng_r128.yaml](templates/experiments/ng_r128.yaml)
- [adafactor_momentum.yaml](templates/experiments/adafactor_momentum.yaml)
- [xng2_col.yaml](templates/experiments/xng2_col.yaml)
- [rmsprop.yaml](templates/experiments/rmsprop.yaml)
- [xnormgrad1.yaml](templates/experiments/xnormgrad1.yaml)
- [adafactor_r128.yaml](templates/experiments/adafactor_r128.yaml)
- [sgd.yaml](templates/experiments/sgd.yaml)
- [rmspropm.yaml](templates/experiments/rmspropm.yaml)
- [xnormgrad3-r128.yaml](templates/experiments/xnormgrad3-r128.yaml)
- [xng2.yaml](templates/experiments/xng2.yaml)
- [rmspropc.yaml](templates/experiments/rmspropc.yaml)
- [control.yaml](templates/experiments/control.yaml)

Default Configuration: control.yaml

Active Configuration: hfadafactor.yaml

## Included Templates
- [experiments/hfadafactor.yaml](templates/experiments/hfadafactor.yaml)
    - [project.yaml](templates/project.yaml)
        - [models/bigger.yaml](templates/models/bigger.yaml)
            - [tokenizers/tiny_8k.yaml](../../../templates/tiny_experiments/tokenizers/tiny_8k.yaml)
            - [models/dynamic_causal_transformer.yaml](../../../templates/modellib/models/dynamic_causal_transformer.yaml)
                - [models/abstract/dynamic_causal_lm.yaml](../../../templates/base/models/abstract/dynamic_causal_lm.yaml)
                    - [models/abstract/custom_causal_lm.yaml](../../../templates/base/models/abstract/custom_causal_lm.yaml)
                        - [models/abstract/base_language_model.yaml](../../../templates/base/models/abstract/base_language_model.yaml)
                            - [inc/formatting.jinja](../../../templates/base/inc/formatting.jinja)
        - [projects/tiny.yaml](../../../templates/tiny_experiments/projects/tiny.yaml)
            - [datasets/tiny/tiny_stories_abridged.yaml](../../../templates/tiny_experiments/datasets/tiny/tiny_stories_abridged.yaml)
                - [datasets/tiny/tiny_stories.yaml](../../../templates/tiny_experiments/datasets/tiny/tiny_stories.yaml)
                    - [datasets/abstract/base_datasets.yaml](../../../templates/base/datasets/abstract/base_datasets.yaml)
            - [prompts/tiny_stories.yaml](../../../templates/tiny_experiments/prompts/tiny_stories.yaml)
            - [types/training_script/causal_lm/causal_lm.yaml](../../../templates/base/types/training_script/causal_lm/causal_lm.yaml)
                - [trainers/trainer.yaml](../../../templates/base/trainers/trainer.yaml)
                    - [trainers/base_trainer.yaml](../../../templates/base/trainers/base_trainer.yaml)
                        - [trainers/minimal_trainer.yaml](../../../templates/base/trainers/minimal_trainer.yaml)
                - [callbacks/loggers.yaml](../../../templates/base/callbacks/loggers.yaml)
                    - [callbacks/base_callbacks.yaml](../../../templates/base/callbacks/base_callbacks.yaml)
                - [models/abstract/load_model.yaml](../../../templates/base/models/abstract/load_model.yaml)
                    - [models/abstract/causal_lm_from_pretrained.yaml](../../../templates/base/models/abstract/causal_lm_from_pretrained.yaml)
                - [types/training_script/training_script.yaml](../../../templates/base/types/training_script/training_script.yaml)
                    - [types/type.yaml](../../../templates/base/types/type.yaml)
                        - [base_directories.yaml](../../../forgather_workspace/base_directories.yaml)
            - [tiny.callbacks](../../../templates/tiny_experiments/projects/tiny.yaml)
            - [tiny.model_config](../../../templates/tiny_experiments/projects/tiny.yaml)
                - [models/tiny/tiny_causal.yaml](../../../templates/tiny_experiments/models/tiny/tiny_causal.yaml)
                    - [tokenizers/tiny_2k.yaml](../../../templates/tiny_experiments/tokenizers/tiny_2k.yaml)
            - [tiny.trainer_config](../../../templates/tiny_experiments/projects/tiny.yaml)
        - [project.dataset_config](templates/project.yaml)
        - [project.trainer_config](templates/project.yaml)
### Config Metadata:

```python
{'config_class': 'type.training_script.causal_lm',
 'config_description': 'HF Adafactor',
 'config_name': 'HF Adafactor',
 'create_new_model': 'True',
 'datasets_dir': '/home/dinalt/ai_assets/forgather/datasets',
 'eval': 'False',
 'forgather_dir': '/home/dinalt/ai_assets/forgather',
 'logging_dir': './output_models/bigger_cp/runs/hf_adafactor_2025-05-18T03-38-25',
 'model_src_dir': '/home/dinalt/ai_assets/forgather/model_src',
 'models_dir': './output_models',
 'output_dir': './output_models/bigger_cp',
 'project_dir': '.',
 'save_model': 'False',
 'tokenizers_dir': '/home/dinalt/ai_assets/forgather/tokenizers',
 'train': 'True',
 'workspace_root': '/home/dinalt/ai_assets/forgather'}

```

## Modules
- [./output_models/bigger_cp/dynamic_causal_transformer.py](output_models/bigger_cp/dynamic_causal_transformer.py) : DynamicCasualLM
    - [/home/dinalt/ai_assets/forgather/examples/trainers/optimizers/./output_models/bigger_cp/dynamic_causal_transformer.py](output_models/bigger_cp/dynamic_causal_transformer.py) : dynamic_causal_transformer
        - [/home/dinalt/ai_assets/forgather/model_src/bits/causal_alibi_attn.py](../../../model_src/bits/causal_alibi_attn.py) : dynamic_causal_transformer.causal_alibi_attn
        - [/home/dinalt/ai_assets/forgather/model_src/bits/causal_lm.py](../../../model_src/bits/causal_lm.py) : dynamic_causal_transformer.causal_lm
        - [/home/dinalt/ai_assets/forgather/model_src/bits/causal_loss.py](../../../model_src/bits/causal_loss.py) : dynamic_causal_transformer.causal_loss
        - [/home/dinalt/ai_assets/forgather/model_src/bits/feedforward_layer.py](../../../model_src/bits/feedforward_layer.py) : dynamic_causal_transformer.feedforward_layer
        - [/home/dinalt/ai_assets/forgather/model_src/bits/init_weights.py](../../../model_src/bits/init_weights.py) : dynamic_causal_transformer.init_weights
        - [/home/dinalt/ai_assets/forgather/model_src/bits/input_encoder.py](../../../model_src/bits/input_encoder.py) : dynamic_causal_transformer.input_encoder
        - [/home/dinalt/ai_assets/forgather/model_src/bits/layer_stack.py](../../../model_src/bits/layer_stack.py) : dynamic_causal_transformer.layer_stack
        - [/home/dinalt/ai_assets/forgather/model_src/bits/null_pe.py](../../../model_src/bits/null_pe.py) : dynamic_causal_transformer.null_pe
        - [/home/dinalt/ai_assets/forgather/model_src/bits/post_ln_layer.py](../../../model_src/bits/post_ln_layer.py) : dynamic_causal_transformer.post_ln_layer
- [./output_models/bigger_cp/dynamic_causal_transformer.py](output_models/bigger_cp/dynamic_causal_transformer.py) : DynamicCausalLMConfig
- [./src/adafactor.py](src/adafactor.py) : Adafactor
    - [/home/dinalt/ai_assets/forgather/examples/trainers/optimizers/./src/adafactor.py](src/adafactor.py) : adafactor
## Output Targets
- meta
- main
- model_code_writer
- distributed_env
- model
- trainer
- train_dataset
- eval_dataset
- data_collator
- trainer_callbacks
- trainer_args
- optimizer
- lr_scheduler
- model_constructor_args
- tokenizer

## Preprocessed Config

```yaml
#---------------------------------------
#              HF Adafactor              
#---------------------------------------
# 2025-05-18T03:38:25
# Description: HF Adafactor
# Project Dir: /home/dinalt/ai_assets/forgather/examples/trainers/optimizers
# Current Working Dir: "/home/dinalt/ai_assets/forgather/examples/trainers/optimizers"
# Forgather Config Dir: "/home/dinalt/.config/forgather"
# Model: bigger_cp
# Hostname: hal9000
# Versions:
#     python: 3.10.13
#     torch: 2.7.0
#     transformers: 4.51.3
#     accelerate: 1.7.0

############# Config Vars ##############

# ns.forgather_dir: "/home/dinalt/ai_assets/forgather"
# ns.models_dir: "/home/dinalt/ai_assets/forgather/examples/trainers/optimizers/output_models"
# ns.project_model_src_dir: "/home/dinalt/ai_assets/forgather/examples/trainers/optimizers/model_src"
# ns.tokenizers_dir: "/home/dinalt/ai_assets/forgather/tokenizers"
# ns.datasets_dir: "/home/dinalt/ai_assets/forgather/datasets"
# ns.model_src_dir: "/home/dinalt/ai_assets/forgather/model_src"
# ns.output_dir: "./output_models/bigger_cp"
# ns.logging_dir: "./output_models/bigger_cp/runs/hf_adafactor_2025-05-18T03-38-25"
# ns.create_new_model: True
# ns.save_model: False
# ns.train: True
# ns.eval: False
# ns.trust_remote_code: True

####### Distributed Environment ########

.define: &distributed_env !singleton:forgather.ml.distributed:DistributedEnvironment@distributed_env

############# Dependencies #############

# The model will be given the following prompts for text-gen at regular intervals.
.define: &testprompts !list:@testprompts
    # Test prompts from "https://arxiv.org/abs/2305.07759"
    - "Alice was so tired when she got back home so she went"
    - "Jack and Lily liked to watch the moon at night. They noticed that the moon changed its shape every night. Sometimes the moon was big and round, and sometimes it was"
    - "Jack and Lily saw a rainbow after a rainy day.They were amazed by the colors. Jack said, \"Look, Lily. A rainbow has"
    - "Jack wanted to read a book, so he went to"
    - "\"Can cows fly?\" Alice asked her mother."
    - "\"What do birds like to eat?\" Tom asked his mother."
    - "\"What language do they speak in France?\" Tom asked his mother."
    - "If I throw a ball up in the air, eventually it will"
    - "It was winter and cold outside so his mother told him, \"You should"
    - "Lily likes cats and dogs. She asked her mom for a dog and her mom said no, so instead she asked"
    - "Jack told Mary, \"If you give me your banana, I'll give you my apple.\" Mary gave Jack her Banana, so"
    - "On weekends Jack went to visit his grandmother whereas on weekdays he would go to school. Last weekend, when Jack was on his way to"
    - "Lily and Ben were having an argument. Ben said that cake is much better than ice cream and Lily said that"
    - "Lily and Ben are having an argument. They are trying to decide between the park and the swimming pool. Ben says, \"I want to go to the park\". Lily says"
    - "Jack's mother was not home, and his father was at home. When Jack came home, he said hello to"
    - "Lily doesn't like swimming. When her father wants to take her to the swimming pool, she says"
    - "Both Ben and Lily wanted cake. Father said that there was only one piece of cake left. They"
    - "Ben went to visit Lily in her house, but she was not at home. Ben knocked on the door,"

# Conservative text-generation parameters.
.define: &generation_config !dict:@generation_config
    identity: generation_config
    do_sample: True
    top_k: 20
    top_p: 0.9
    temperature: 0.7
    repitition_penalty: 1.15

################ Model #################

# https://huggingface.co/docs/transformers/en/model_doc/auto
.define: &model_constructor_args {}

#-- set model_def.name = "Tiny Causal"
    #-- set model_def.description = "A scaled-down version of the base Causal Transformer"
    #-- set model_def.short_name = "tiny_causal_transformer"



# Name: Dynamic Causal Transformer
# Description: A vanilla causal transformer model.
# model_def.cls = "DynamicCasualLM"
# model_def.cfg_cls = "DynamicCausalLMConfig"
# model_def.config_path = "/home/dinalt/ai_assets/forgather/examples/trainers/optimizers/output_models/bigger_cp/dynamic_causal_transformer.py"
# model_def.model_path = "/home/dinalt/ai_assets/forgather/examples/trainers/optimizers/output_models/bigger_cp/dynamic_causal_transformer.py"
# model_def.short_name = "dynamic_causal_transformer"
# model_def.model_type = "forgather-dynamic-causal-dynamic_causal_transformer"
# model_def.model_path = "./output_models/bigger_cp/dynamic_causal_transformer.py"
# model_def.model_template_searchpath = "/home/dinalt/ai_assets/forgather/templates/dynamic_models"
# model_def.model_template_name = "causal_lm.py"
# model_def.name_policy = "named"

# **Tokenizer**

# Load custom tokenizer from sub-project definition
.define: &tokenizer !singleton:forgather.ml.construct:load_from_config@tokenizer
    project_dir: "/home/dinalt/ai_assets/forgather/examples/tokenizers/tiny_stories_bpe"
    config_template: "8k.yaml"

# **Model Config**

.define: &model_submodule_searchpath
    - "/home/dinalt/ai_assets/forgather/model_src/bits"
    - "./output_models/bigger_cp"

.define: &loss_fn_factory !lambda:.causal_loss:CausalLoss@loss_fn_factory []

.define: &layer_norm_factory !lambda:torch.nn:LayerNorm@layer_norm_factory
    normalized_shape: !var "hidden_size"

.define: &feedforward_factory !lambda:.feedforward_layer:FeedforwardLayer@feedforward_factory
    d_model: !var "hidden_size"
    d_feedforward: !var "dim_feedforward"
    dropout: !var "activation_dropout"

.define: &attention_factory !lambda:.causal_alibi_attn:CausalAlibiAttn@attention_factory
    d_model: !var "hidden_size"
    num_heads: !var "num_attention_heads"
    dropout: !var "attention_dropout"
    bias: false
    trainable_alibi: false
    alt_alibi_init: true

.define: &layer_factory !lambda:.post_ln_layer:PostLNLayer@layer_factory
    feedforward_factory: *feedforward_factory
    attention_factory: *attention_factory
    norm_factory: *layer_norm_factory
    dropout: !var "layer_dropout"
    residual_dropout: !var "residual_dropout"

.define: &layer_stack_factory !lambda:.layer_stack:LayerStack@layer_stack_factory
    layer_factory: *layer_factory
    num_hidden_layers: !var "num_hidden_layers"

.define: &output_decoder_factory !lambda:torch.nn:Linear@output_decoder_factory
    - !var "hidden_size"
    - !var "vocab_size"

.define: &positional_encoder_factory !lambda:.null_pe:NullPE


.define: &input_encoder_factory !lambda:.input_encoder:InputEncoder@input_encoder_factory
    d_model: !var "hidden_size"
    vocab_size: !var "vocab_size"
    dropout: !var "embedding_dropout"
    positional_encoder_factory: *positional_encoder_factory

.define: &init_weights_factory !lambda:.init_weights:InitWeights@init_weights_factory
    std: !var "initializer_range"

.define: &model_factory !singleton:.causal_lm:CasualLM@model_factory
    loss_fn_factory: *loss_fn_factory
    input_encoder_factory: *input_encoder_factory
    output_decoder_factory: *output_decoder_factory
    layer_stack_factory: *layer_stack_factory
    init_weights_factory: *init_weights_factory

.define: &model_code_generator !meta:forgather.codegen:generate_code@model_code_generator
    searchpath: "/home/dinalt/ai_assets/forgather/templates/dynamic_models"
    template_name: "causal_lm.py"
    name_policy: "named"
    obj: *model_factory
    # Template args
    model_type: "forgather-dynamic-causal-dynamic_causal_transformer"

.define: &model_code_writer !singleton:forgather.ml.construct:write_file@model_code_writer
    data: *model_code_generator
    output_file: "./output_models/bigger_cp/dynamic_causal_transformer.py"
    return_value: "Model constructor generated by Forgather 1.0"    

.define: &model_config !singleton:./output_models/bigger_cp/dynamic_causal_transformer.py:DynamicCausalLMConfig@model_config
    submodule_searchpath: *model_submodule_searchpath
    # Set auto-map for custom model; this ensures that the source code stays with the model.
    auto_map:
        AutoConfig: "dynamic_causal_transformer.DynamicCausalLMConfig"
        AutoModel: "dynamic_causal_transformer.DynamicCasualLM"
    # Get the vocab-size from the tokenizer definition.
    vocab_size: !singleton:len [ *tokenizer ]
    pad_token_id: !singleton:getattr [ *tokenizer, 'pad_token_id' ]
    bos_token_id: !singleton:getattr [ *tokenizer, 'bos_token_id' ]
    eos_token_id: !singleton:getattr [ *tokenizer, 'eos_token_id' ]
    # Add dependency on code generator
    code_generator: *model_code_writer
    hidden_size: 512
    num_attention_heads: 8
    num_hidden_layers: 6
    max_sequence_length: !singleton:getattr
        - *tokenizer
        - "model_max_length"
    dim_feedforward: 2048
    initializer_range: 0.02
    embedding_dropout: 0.10
    layer_dropout: 0.10
    residual_dropout: 0.0
    attention_dropout: 0.0
    activation_dropout: 0.0
    # Project Overrides
    hidden_size: 512
    num_attention_heads: 8
    num_hidden_layers: 8
    dim_feedforward: 2048
    initializer_range: 0.02
    embedding_dropout: 0.10
    layer_dropout: 0.10

# **Model Constructor**

.define: &pretrained_model !singleton:./output_models/bigger_cp/dynamic_causal_transformer.py:DynamicCasualLM@pretrained_model
    args:
        - *model_config
    kwargs:
        submodule_searchpath: *model_submodule_searchpath
        <<: *model_constructor_args

.define: &model !singleton:forgather.ml.construct:dependency_list@model
    - *pretrained_model
    - !singleton:forgather.ml.construct:copy_package_files
        - "./output_models/bigger_cp"
        - *model_config
    - !singleton:forgather.ml.construct:copy_package_files
        - "./output_models/bigger_cp"
        - *pretrained_model

############### Datasets ###############

# Name: TinyStories Abridged
# Define: Abridged to 10% of original size; Dataset containing synthetically generated (by GPT-3.5 and GPT-4) short stories that only use a small vocabulary.
# Source: https://arxiv.org/abs/2305.07759
# Train Dataset: "roneneldan/TinyStories" : "train"
# Eval Dataset: "roneneldan/TinyStories" : "validation"

# **Source Datasets**

.define: &train_source_dataset !singleton:datasets:load_dataset@train_source_dataset
    - "roneneldan/TinyStories"

.define: &eval_source_dataset !singleton:datasets:load_dataset@eval_source_dataset
    - "roneneldan/TinyStories"

# **Dataset Splits**

.define: &train_dataset_split !singleton:operator:getitem
    - *train_source_dataset
    - "train"

.define: &eval_dataset_split !singleton:operator:getitem
    - *train_source_dataset
    - "validation"

# **Tokenize Args**

.define: &tokenize_args
    truncation: True
    # project overrides
    max_length: 512

# **Tokenized Datasets**

.define: &train_dataset !singleton:forgather.ml.datasets:tokenize_dataset@train_dataset
    dataset: *train_dataset_split
    tokenizer: *tokenizer
    select_range: 0.1
    desc: "Tokenizing train"
    fn_kwargs:
        <<: *tokenize_args

.define: &eval_dataset !singleton:forgather.ml.datasets:tokenize_dataset@eval_dataset
    dataset: *eval_dataset_split
    tokenizer: *tokenizer
    select_range: 500
    desc: "Tokenizing validation split"
    fn_kwargs:
        <<: *tokenize_args

############ Data Collator #############

# Data collator for causal model
# Batches are dynamically padded to longest sequence
# labels are set to input_ids, with pad tokens set to -100
# https://huggingface.co/docs/transformers/en/main_classes/data_collator#transformers.DataCollatorForLanguageModeling
.define: &data_collator !singleton:transformers:DataCollatorForLanguageModeling@data_collator
    args:
        - *tokenizer
    kwargs:
        mlm: False
        return_tensors: pt

########## Trainer Callbacks ###########

# **Dependencies**

# Experiment tracking: Tensorboard SummaryWriter
.define: &summary_writer !singleton:torch.utils.tensorboard:SummaryWriter
    - "./output_models/bigger_cp/runs/hf_adafactor_2025-05-18T03-38-25"

# Additional data to record to experiment loggers
.define: &experiment_info !dict:@experiment_info
    date: "2025-05-18T03:38:25"
    name: "HF Adafactor"
    description: "HF Adafactor"
    config: !var "pp_config"
    versions: {'python': '3.10.13', 'torch': '2.7.0', 'transformers': '4.51.3', 'accelerate': '1.7.0'}

.define: &text_gen_callback_args
    summary_writer: *summary_writer
    prompts: *testprompts
    generation_config: *generation_config
    max_new_tokens: 40
    generation_steps: 2000

# **Callback List**

.define: &trainer_callbacks !list:@trainer_callbacks
    # Log all training output to JSON
    - !singleton:forgather.ml.json_logger:JsonLogger
        <<: *experiment_info
    # Log configuration and metrics to Tensorboard file
    - !singleton:forgather.ml.tb_logger:TBLogger
        args: [ *summary_writer ]
        kwargs:
            <<: *experiment_info
    - !singleton:forgather.ml.textgen_callback:TextgenCallback
        <<: *text_gen_callback_args

############## Optimizer ###############

.define: &optimizer !lambda:./src/adafactor.py:Adafactor
    kwargs:
        lr: 0.0005
        scale_parameter: False
        relative_step: False
############# LR Scheduler #############

.define: &lr_scheduler ~

############### Trainer ################

# Name: Custom forgather.ml.trainer.Trainer
# Description: A lightweight, extensible trainer; does not support multiple GPUs

# **Trainer Args**

.define: &trainer_args
    # Minimal Trainer Defaults
    # https://huggingface.co/docs/transformers/en/main_classes/trainer#transformers.TrainingArguments
    output_dir: "./output_models/bigger_cp"
    logging_dir: "./output_models/bigger_cp/runs/hf_adafactor_2025-05-18T03-38-25"
    logging_steps: 500
    per_device_train_batch_size: 16
    per_device_eval_batch_size: 32
    learning_rate: 5.0e-5
    num_train_epochs: 1
    # Base Trainer Defaults
    # https://huggingface.co/docs/transformers/en/main_classes/trainer#transformers.TrainingArguments
    overwrite_output_dir: True
    eval_steps: 100
    eval_strategy: "steps"
    save_strategy: "no"
    logging_strategy: "steps"

    # Tiny Project Overrides
    per_device_train_batch_size: 32
    per_device_eval_batch_size: 64
    logging_steps: 100
    eval_steps: 500
    learning_rate: 1.0e-3
    num_train_epochs: 1

    # project overrides
    per_device_train_batch_size: 32
    per_device_eval_batch_size: 32

# **Trainer Constructor**

.define: &trainer !singleton:forgather.ml.trainer:Trainer@trainer
    model: *model
    args: !singleton:forgather.ml.trainer_types:TrainingArguments@trainer_args
        <<: *trainer_args
    data_collator: *data_collator
    train_dataset: *train_dataset
    eval_dataset: *eval_dataset
    processing_class: *tokenizer
    callbacks: *trainer_callbacks
    optimizer_factory: *optimizer
    lr_scheduler_factory: *lr_scheduler

#---------------------------------------
#          Configuration Output          
#---------------------------------------
meta: &meta_output !dict:@meta
    config_name: "HF Adafactor"
    config_description: "HF Adafactor"
    config_class: "type.training_script.causal_lm"
    project_dir: "."
    workspace_root: "/home/dinalt/ai_assets/forgather"
    forgather_dir: "/home/dinalt/ai_assets/forgather"
    models_dir: "./output_models"
    tokenizers_dir: "/home/dinalt/ai_assets/forgather/tokenizers"
    datasets_dir: "/home/dinalt/ai_assets/forgather/datasets"
    output_dir: "./output_models/bigger_cp"
    model_src_dir: "/home/dinalt/ai_assets/forgather/model_src"
    logging_dir: "./output_models/bigger_cp/runs/hf_adafactor_2025-05-18T03-38-25"
    create_new_model: "True"
    save_model: "False"
    train: "True"
    eval: "False"

main: !singleton:forgather.ml.training_script:TrainingScript@training_script
    meta: *meta_output
    do_save: False
    do_train: True
    do_eval: False
    # Init distributed envrionment before initializing anyting which depends on it.
    distributed_env: *distributed_env
    trainer: *trainer
    pp_config: !var "pp_config"

model_code_writer: *model_code_writer
distributed_env: *distributed_env
model: *model
trainer: *trainer
train_dataset: *train_dataset
eval_dataset: *eval_dataset
data_collator: *data_collator
trainer_callbacks: *trainer_callbacks
trainer_args: *trainer_args
optimizer: *optimizer
lr_scheduler: *lr_scheduler
model_constructor_args: *model_constructor_args
tokenizer: *tokenizer

```



In [4]:
import torchao
torchao.optim.Adam8bit

In [2]:
from forgather.ml.trainer import Trainer
from forgather.ml.trainer_types import TrainingArguments
from forgather.ml.training_script import TrainingScript
from pprint import pp
import torch
from forgather.project import Project

# Load default baseline config
proj = Project("norm_grad.yaml")

torch.manual_seed(42)
outputs = proj([
    "meta",
    "distributed_env",
    "train_dataset",
    "eval_dataset",
    "trainer_args",
    "model",
    "data_collator",
    "trainer_callbacks",
    "tokenizer",
    "optimizer",
    "trainer",
    "main",
])

training_args = outputs["trainer_args"] | dict(
    #num_train_epochs = 1,
    #learning_rate = 1.0e-3,
    #lr_scheduler_type=None,
)

training_args = TrainingArguments(**training_args)
pp(training_args)

TrainingArguments(output_dir='./output_models/bigger_cp',
                  logging_dir='./output_models/bigger_cp/runs/norm_grad_b32_lr1e-3_2025-05-16T04-03-59',
                  logging_steps=100,
                  per_device_eval_batch_size=32,
                  per_device_train_batch_size=32,
                  learning_rate=0.001,
                  num_train_epochs=1,
                  device=None,
                  max_steps=-1,
                  lr_scheduler_type=None,
                  warmup_steps=0,
                  eval_steps=500,
                  save_steps=500,
                  dataloader_num_workers=0,
                  dataloader_pin_memory=True,
                  dataloader_persistent_workers=False,
                  dataloader_prefetch_factor=None,
                  dataloader_drop_last=False,
                  overwrite_output_dir=True,
                  seed=-1,
                  eval_strategy=<IntervalStrategy.STEPS: 'steps'>,
                  logging_strategy=<

In [3]:
outputs["main"].run()

**** Training Script Started *****
config_name: Norm Grad
config_description: Norm Grad
output_dir: ./output_models/bigger_cp
logging_dir: ./output_models/bigger_cp/runs/norm_grad_b32_lr1e-3_2025-05-16T04-03-59
not compiling model
Calling optimizer factory


  0%|                                                                                                         …

total_examples: 212,000
total_train_samples: 212,000
per_device_train_batch_size: 32
actual_per_device_batch_size: 32
total_train_batch_size: 32
max_steps: 6,625
total_parameters: 33.4M
trainable_parameters: 33.4M
model:
DynamicCasualLM(
  (causal_lm): CasualLM(
    loss_fn=CausalLoss(), init_weights=InitWeights(std=0.02)
    (input_encoder): InputEncoder(
      d_model=512, vocab_size=8000, embedding_scale=22.627416997969522
      (dropout): Dropout(p=0.1, inplace=False)
      (embedding): Embedding(8000, 512)
      (positional_encoder): NullPE()
    )
    (output_decoder): Linear(in_features=512, out_features=8000, bias=True)
    (layer_stack): LayerStack(
      (layers): ModuleList(
        (0-7): 8 x PostLNLayer(
          (feedforward): FeedforwardLayer(
            d_model=512, d_feedforward=2048
            (linear1): Linear(in_features=512, out_features=2048, bias=True)
            (dropout): Identity()
            (activation): ReLU()
            (linear2): Linear(in_features=

  0%|                                                                                                         …

2025-05-16 04:04:55          500  0.08  eval-loss:  6.57636   
2025-05-16 04:05:08          600  0.09  epoch: 0.09057 loss: 6.198 


KeyboardInterrupt: 

In [1]:
import torch
from pickle import dump

# tell CUDA to start recording memory allocations
torch.cuda.memory._record_memory_history(enabled='all')

In [4]:
from pickle import dump

# save a snapshot of the memory allocations
s = torch.cuda.memory._snapshot()
with open(f"snapshot.pickle", "wb") as f:
    dump(s, f)

# tell CUDA to stop recording memory allocations now
torch.cuda.memory._record_memory_history(enabled=None)

In [ ]:
# Snap
class ProjectorOptim(Optimizer):
    """
    Implements Adam algorithm with weight decay fix as introduced in [Decoupled Weight Decay
    Regularization](https://arxiv.org/abs/1711.05101).

    Parameters:
        params (`Iterable[nn.parameter.Parameter]`):
            Iterable of parameters to optimize or dictionaries defining parameter groups.
        lr (`float`, *optional*, defaults to 0.001):
            The learning rate to use.
        betas (`Tuple[float,float]`, *optional*, defaults to `(0.9, 0.999)`):
            Adam's betas parameters (b1, b2).
        eps (`float`, *optional*, defaults to 1e-06):
            Adam's epsilon for numerical stability.
        weight_decay (`float`, *optional*, defaults to 0.0):
            Decoupled weight decay to apply.
        correct_bias (`bool`, *optional*, defaults to `True`):
            Whether or not to correct bias in Adam (for instance, in Bert TF repository they use `False`).
    """

    def __init__(
        self,
        params: Iterable[nn.parameter.Parameter],
        lr: float = 1e-3,
        betas: Tuple[float, float] = (0.9, 0.999),
        eps: float = 1e-6,
        weight_decay: float = 0.0,
        correct_bias: bool = True,
    ):
        require_version("torch>=1.5.0")  # add_ with alpha
        if lr < 0.0:
            raise ValueError(f"Invalid learning rate: {lr} - should be >= 0.0")
        if not 0.0 <= betas[0] < 1.0:
            raise ValueError(f"Invalid beta parameter: {betas[0]} - should be in [0.0, 1.0)")
        if not 0.0 <= betas[1] < 1.0:
            raise ValueError(f"Invalid beta parameter: {betas[1]} - should be in [0.0, 1.0)")
        if not 0.0 <= eps:
            raise ValueError(f"Invalid epsilon value: {eps} - should be >= 0.0")
        defaults = {"lr": lr, "betas": betas, "eps": eps, "weight_decay": weight_decay, "correct_bias": correct_bias}
        super().__init__(params, defaults)

    @torch.no_grad()
    def step(self, closure: Callable = None):
        """
        Performs a single optimization step.

        Arguments:
            closure (`Callable`, *optional*): A closure that reevaluates the model and returns the loss.
        """
        loss = None
        if closure is not None:
            loss = closure()

        for group in self.param_groups:
            for p in group["params"]:
                if p.grad is None:
                    continue
                if "proj_args" not in group:
                    self.update_adamw(group, p)
                else:
                    self.update_projection(group, p)

        return loss

    def update_adamw(self, group, p):
        grad = p.grad
        if grad.is_sparse:
            raise RuntimeError("Adam does not support sparse gradients, please consider SparseAdam instead")

        state = self.state[p]
        
        if "step" not in state:
            state["step"] = 0

        # State initialization
        if "exp_avg" not in state:
            # Exponential moving average of gradient values
            state["exp_avg"] = torch.zeros_like(grad)
            # Exponential moving average of squared gradient values
            state["exp_avg_sq"] = torch.zeros_like(grad)

        exp_avg, exp_avg_sq = state["exp_avg"], state["exp_avg_sq"]
        beta1, beta2 = group["betas"]

        state["step"] += 1

        # Decay the first and second moment running average coefficient
        # In-place operations to update the averages at the same time
        exp_avg.mul_(beta1).add_(grad, alpha=(1.0 - beta1))
        exp_avg_sq.mul_(beta2).addcmul_(grad, grad, value=1.0 - beta2)
        denom = exp_avg_sq.sqrt().add_(group["eps"])

        step_size = group["lr"]
        if group["correct_bias"]:  # No bias correction for Bert
            bias_correction1 = 1.0 - beta1 ** state["step"]
            bias_correction2 = 1.0 - beta2 ** state["step"]
            step_size = step_size * math.sqrt(bias_correction2) / bias_correction1

        # compute norm gradient
        norm_grad = exp_avg / denom
        
        p.add_(norm_grad, alpha=-step_size)

        # Just adding the square of the weights to the loss function is *not*
        # the correct way of using L2 regularization/weight decay with Adam,
        # since that will interact with the m and v parameters in strange ways.
        #
        # Instead we want to decay the weights in a manner that doesn't interact
        # with the m/v parameters. This is equivalent to adding the square
        # of the weights to the loss with plain (non-momentum) SGD.
        # Add weight decay at the end (fixed version)
        if group["weight_decay"] > 0.0:
            p.add_(p, alpha=(-group["lr"] * group["weight_decay"]))

    def update_projection(self, group, p):
        grad = p.grad
        state = self.state[p]
        
        if "step" not in state:
            state["step"] = 0

        beta1, beta2 = group["betas"]
        
        # Projection
        if "projector" not in state:
            projector = state["projector"] = SubspaceProjector(
                grad,
                **group["proj_args"],
            )
        else:
            projector = state["projector"]
            projector.update(grad)
        
        grad = projector.down(grad)
        match projector.proj_type:
            case "right":
                S = grad.square().mean(dim=1).sqrt().view(-1, 1)
            case "left":
                S = grad.square().mean(dim=0).sqrt()
            case _:
                raise Exception("Unknown projection type")
        
        state["step"] += 1

        norm_grad = grad / (S + group["eps"])
        
        # Project up
        norm_grad = projector.up(norm_grad)
        
        p.add_(norm_grad, alpha=(-group["lr"]))

        if group["weight_decay"] > 0.0:
            p.add_(p, alpha=(-group["lr"] * group["weight_decay"]))

In [ ]:
import math
import warnings
from typing import Callable, Iterable, Tuple

import torch
import torch.nn.functional as F
from torch import nn
from torch.optim import Optimizer

i = torch.randn(8).abs()
i

In [84]:
rows = 4
cols = 8
eps = 1e-9

r_ = torch.randn(rows)
c_ = torch.randn(cols)

# Rank-1 matrix
M = torch.outer(r_, c_)
M_square = M ** 2

r_, c_, M, M_square

(tensor([-0.5377, -0.8546,  0.4564,  0.2159]),
 tensor([ 3.0695, -1.0949, -0.6703, -0.0544,  0.4961,  0.5092, -0.5062,  0.7882]),
 tensor([[-1.6505,  0.5887,  0.3604,  0.0292, -0.2667, -0.2738,  0.2722, -0.4238],
         [-2.6231,  0.9357,  0.5728,  0.0465, -0.4239, -0.4352,  0.4326, -0.6736],
         [ 1.4010, -0.4997, -0.3059, -0.0248,  0.2264,  0.2324, -0.2310,  0.3598],
         [ 0.6628, -0.2364, -0.1447, -0.0117,  0.1071,  0.1100, -0.1093,  0.1702]]),
 tensor([[2.7242e+00, 3.4662e-01, 1.2990e-01, 8.5508e-04, 7.1151e-02, 7.4975e-02,
          7.4086e-02, 1.7965e-01],
         [6.8809e+00, 8.7551e-01, 3.2810e-01, 2.1598e-03, 1.7972e-01, 1.8938e-01,
          1.8713e-01, 4.5376e-01],
         [1.9627e+00, 2.4974e-01, 9.3590e-02, 6.1608e-04, 5.1264e-02, 5.4019e-02,
          5.3378e-02, 1.2943e-01],
         [4.3928e-01, 5.5894e-02, 2.0947e-02, 1.3789e-04, 1.1473e-02, 1.2090e-02,
          1.1947e-02, 2.8969e-02]]))

In [66]:
r = M_square.mean(dim=1)
r

tensor([0.0338, 0.1305, 0.4477, 0.0801])

In [67]:
c = M_square.mean(dim=0)
c

tensor([0.1904, 0.0015, 0.0101, 0.0436, 0.3065, 0.1682, 0.6503, 0.0136])

In [68]:
r_factor = 1 / torch.sqrt(r / r.mean(dim=-1, keepdim=True) + eps)
r_factor

tensor([2.2642, 1.1515, 0.6217, 1.4694])

In [69]:
c_factor = 1 / torch.sqrt(c)
c_factor

tensor([ 2.2917, 26.0588,  9.9450,  4.7882,  1.8063,  2.4379,  1.2401,  8.5643])

In [70]:
M_f = torch.outer(r_factor, c_factor)
M_f

tensor([[ 5.1888, 59.0019, 22.5172, 10.8412,  4.0897,  5.5199,  2.8078, 19.3911],
        [ 2.6389, 30.0073, 11.4518,  5.5137,  2.0799,  2.8073,  1.4280,  9.8619],
        [ 1.4246, 16.1996,  6.1823,  2.9766,  1.1229,  1.5156,  0.7709,  5.3240],
        [ 3.3674, 38.2905, 14.6130,  7.0357,  2.6541,  3.5823,  1.8222, 12.5842]])

In [71]:
r_factor = (r / r.mean(dim=-1, keepdim=True)).rsqrt_().unsqueeze(-1)
c_factor = c.unsqueeze(-2).rsqrt()
torch.mul(r_factor, c_factor)

tensor([[ 5.1888, 59.0019, 22.5172, 10.8412,  4.0897,  5.5199,  2.8078, 19.3911],
        [ 2.6389, 30.0073, 11.4518,  5.5137,  2.0799,  2.8073,  1.4280,  9.8619],
        [ 1.4246, 16.1996,  6.1823,  2.9766,  1.1229,  1.5156,  0.7709,  5.3240],
        [ 3.3674, 38.2905, 14.6130,  7.0357,  2.6541,  3.5823,  1.8222, 12.5842]])

In [73]:
M_square = M ** 2
r = M_square.mean(dim=1)
c = M_square.mean(dim=0)
r_factor = torch.rsqrt(r / r.mean())
c_factor = torch.rsqrt(c)
M_f = torch.outer(r_factor, c_factor)
M_f

tensor([[ 5.1888, 59.0019, 22.5172, 10.8412,  4.0897,  5.5199,  2.8078, 19.3911],
        [ 2.6389, 30.0073, 11.4518,  5.5137,  2.0799,  2.8073,  1.4280,  9.8619],
        [ 1.4246, 16.1996,  6.1823,  2.9766,  1.1229,  1.5156,  0.7709,  5.3240],
        [ 3.3674, 38.2905, 14.6130,  7.0357,  2.6541,  3.5823,  1.8222, 12.5842]])

In [85]:
# Pure low-rank factorization of M**2
M_square = M ** 2
r = M_square.mean(dim=1)
r /= r.mean() + eps
c = M_square.mean(dim=0)
M_f = torch.outer(r, c)
M_f
#1 / (torch.sqrt(M_f) + eps)

tensor([[2.7242e+00, 3.4662e-01, 1.2990e-01, 8.5508e-04, 7.1151e-02, 7.4975e-02,
         7.4086e-02, 1.7965e-01],
        [6.8809e+00, 8.7551e-01, 3.2810e-01, 2.1598e-03, 1.7972e-01, 1.8938e-01,
         1.8713e-01, 4.5376e-01],
        [1.9627e+00, 2.4973e-01, 9.3590e-02, 6.1608e-04, 5.1264e-02, 5.4019e-02,
         5.3378e-02, 1.2943e-01],
        [4.3928e-01, 5.5894e-02, 2.0947e-02, 1.3789e-04, 1.1473e-02, 1.2090e-02,
         1.1947e-02, 2.8969e-02]])

In [86]:
torch.sqrt(M_f)

tensor([[1.6505, 0.5887, 0.3604, 0.0292, 0.2667, 0.2738, 0.2722, 0.4238],
        [2.6231, 0.9357, 0.5728, 0.0465, 0.4239, 0.4352, 0.4326, 0.6736],
        [1.4010, 0.4997, 0.3059, 0.0248, 0.2264, 0.2324, 0.2310, 0.3598],
        [0.6628, 0.2364, 0.1447, 0.0117, 0.1071, 0.1100, 0.1093, 0.1702]])

In [87]:
# Rank-1 factorization of M
r = M.mean(dim=1)
r /= r.mean() + eps
c = M.mean(dim=0)
M_f = torch.outer(r, c)
M_f

tensor([[-1.6505,  0.5887,  0.3604,  0.0292, -0.2667, -0.2738,  0.2722, -0.4238],
        [-2.6231,  0.9357,  0.5728,  0.0465, -0.4239, -0.4352,  0.4326, -0.6736],
        [ 1.4010, -0.4997, -0.3059, -0.0248,  0.2264,  0.2324, -0.2310,  0.3598],
        [ 0.6628, -0.2364, -0.1447, -0.0117,  0.1071,  0.1100, -0.1093,  0.1702]])